# ui
# overall title
navbarPage(
  id = 'catwiki',
  title = actionLink('title', 'Categorizing Wikipedia'),
  
  # theme
  theme = shinytheme('flatly'),
  
  
  # category comparison page
  tabPanel(
    'Category',
    fluidPage(
      titlePanel('Comparing Networks Generated by Categories'), br(),
      
      # select categories to compare
      selectizeInput(
        inputId = 'cats',
        label = 'Select up to two seed categories to explore.',
        width = '100%',
        multiple = T,
        choices = namekey$title,
        options = list(maxItems = 2)),
      
      # compare category network structure
      mainPanel(
        width = 12,
        tabsetPanel(
          id = 'cattabs',
          
          # network graphs
          tabPanel(
            'Subcategory Networks', br(),
            uiOutput('catnetvis')),
          
          # cluster names
          tabPanel(
            'Cluster Member Comparison', br(),
            uiOutput('clusternames')),
          
          # cluster matrices
          tabPanel(
            'Cluster Comparison Matrices', br(),
            uiOutput('clustermat'))
          )))),
  
  
  # page information page
  tabPanel(
    'Page',
    fluidPage(
      titlePanel('Examining Pages within a Category-Generated Network'), br(),
      
      # select category to look at network for
      selectizeInput(
        inputId = 'pagcats',
        label = 'Select a seed category to explore.',
        width = '100%',
        choices = namekey$title),
    
      # look at either page data or network
      mainPanel(
        width = 12,
        tabsetPanel(
          id = 'pagtabs',
          
          # network graph
          tabPanel('Network Visualization', br(), netvis, br(),
                   includeHTML('text/page_net.txt')),
          
          # node data
          tabPanel('Page Data', br(), datvis, br(),
                   includeHTML('text/page_dat.txt'))
        )))),
  
  
  # about page
  tabPanel(
    'About',
    includeHTML('text/about_gen.txt'), br(),
    tabsetPanel(
      id = 'abouttabs',
      tabPanel(
        'Background',
        includeHTML('text/about_back.txt')),
      tabPanel(
        'Navigation and Data',
        includeHTML('text/about_top.txt'),
        dataTableOutput('name_table'),
        includeHTML('text/about_bot.txt')))
    )
)